name: HuyLQ54-Pipeline-$(Date:yyyyMMddHHmmss)

trigger:
  - main

pool: myAgentPool

variables:
  python.version: "3.7.6"
  # ToDo: Replace the service connection name as used in the DevOps project settings
  azureServiceConnectionId: "myServiceConnection"
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  # Environment name
  environmentName: "test"

stages:
  - stage: Infrastructure
    jobs:
      - job: Terraform
        steps:
          # Install Terraform on the pipeline agent
          - task: TerraformInstaller@0
            displayName: "Terraform installation"
            inputs:
              terraformVersion: "1.2.9"

          # Run Terraform Init
          - task: TerraformTaskV3@3
            displayName: "Terraform init"
            inputs:
              provider: "azurerm"
              command: "init"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/environments/test"
              backendServiceArm: "$(azureServiceConnectionId)"
              backendAzureRmResourceGroupName: "$(resource_group_name)"
              backendAzureRmStorageAccountName: "$(storageAccountName)"
              backendAzureRmContainerName: "$(containerName)"
              backendAzureRmKey: "test.terraform.tfstate"
              commandOptions:
                '-input=false -backend-config="client_id=$(client_id)"
                -backend-config="client_secret=$(client_secret)"
                -backend-config="tenant_id=$(tenant_id)"
                -backend-config="subscription_id=$(subscription_id)"'

            # Run Terraform Validate
          - task: TerraformTaskV3@3
            displayName: Terraform validate
            inputs:
              provider: "azurerm"
              command: "validate"

          # Run Terraform Apply
          - task: TerraformTaskV3@3
            displayName: "Terraform apply"
            inputs:
              provider: "azurerm"
              command: "apply"
              workingDirectory: "$(System.DefaultWorkingDirectory)/terraform/environments/test"
              environmentServiceNameAzureRM: "$(azureServiceConnectionId)"
              commandOptions:
                '-input=false -auto-approve -var="tenant_id=$(tenant_id)"
                -var="subscription_id=$(subscription_id)"
                -var="client_id=$(client_id)"
                -var="client_secret=$(client_secret)"
                -var="public_key=$(public_key)"'
